# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ajtDhSLlUDkR4o47QzrmrsitIm9gDaaS
"""

import numpy as np 
import pandas as pd

df = pd.read_json('IIT5.json')

dft = df.transpose()
dft['Computer Science and Engineering'].apply(pd.Series)

df2 = pd.json_normalize(df['IIT-Jammu'])

df2['Uni'] = 'IIT-Jammu'

df2 = df2.set_index('Uni')

dft.loc['IIT-Dharwad']['Computer Science and Engineering']['Cutoffs']['2021']['Round-1']['GEN Gender-Neutral']

km = []

for i in df.columns:
  for j in dft.columns:
    if(type(dft.loc[i][j]) is dict):
      for k in dft.loc[i][j]:
        if(k == 'Cutoffs'):
          #print('i=',i,'j=',j,'k=',k,'val=',dft.loc[i][j][k]['2021']['Round-1']['GEN Gender-Neutral'])
          a1 = int(dft.loc[i][j][k]['2021']['Round-1']['GEN Gender-Neutral']['Opening'])
          a2 = int(dft.loc[i][j][k]['2021']['Round-1']['GEN Gender-Neutral']['Closing'])
          km.append([a1,a2])
  #print()

import matplotlib.pyplot as plt
# %matplotlib inline

km2 = np.array(km).astype(np.float)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters = 5)

kmeans.fit(km2)

print(kmeans.predict([[1,1]])[0])

import pickle

filename = 'Model.pckl'
pickle.dump(kmeans, open(filename, 'wb'))
#pickle.dump(km2, open(filename, 'wb'))
